//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autos
    {
        public int id { get; set; }
        public string modelo { get; set; }
        public int cod_chasis { get; set; }
        public int precio { get; set; }
        public System.DateTime fecha_llegada { get; set; }
        public int cod_marca { get; set; }
    }
}
